### ISSUE TITLE
Missing logger and util packages. 

### ISSUE THREAD

**Issue by cevansOTBS** [rozd/socket.io-client.as3#3]
The current build is missing the following packages from the source:
skein.logger
skein.utils

It would be great if you could commit those because as of right now this library is broken without those.

Thanks!

**Comment by rozd** [comment]
They are in a separate project: https://github.com/skeinlib/skein/tree/master/skein-logger for `skein.logger` and https://github.com/skeinlib/skein/tree/master/skein-utils for `skein.utils`, but you're right they should be linked as dependencies to this project.
